language: julia
os:
  - linux
julia:
  - 1.0
  - 1.4
  - 1.5
notifications:
  email: false
after_success:
  - julia -e 'ENV["TRAVIS_JULIA_VERSION"] != "1.4" && exit(); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
